### PR TITLE
Messages are removed from the MongoDB by the monitor when no Application...

### PR DESCRIPTION
**Pull request by frsela**
... or Node is located

### CODE REVIEW

**Comment by frsela** [comment]
agree, we can unify the parameter ...
I grep'ed all calls to this method, I think I didn't forget any ;)

**Comment by willyaranda** [comment]
Can you made another pull request (or ament this, I don't know if it's possible) with those fixed? :)

**Comment by willyaranda** [comment]
nice @frsela, if you push another commit to the same branch as this pull request were made in your repository, the commit is automagically added here to review, yay!

**Comment by frsela** [comment]
I'll pull a rebased one.

**Pull request closed without merging**
